FORMAT: 1A
HOST: http://localhost/pablofica/index.php

# PabloFica API

Descrição da Sample.

# Group API

## Sobre [/]

Todo response pode receber token/refresh_token via Header, desde que o token 
enviado na request tenha expirado. 

### Pronto:
- Autenticação via token (jwt)
- Login
- Paciente
- Exame
- Consulta
- Exercicio
- Imc

### Não Pronto:

- Tanta coisa, que vai levar muito tempo para descrever... 😅




# Group Login

## Login [/login]

### login( ) [POST]

+ Request login 
        
    + Schema

            {}

    + Attributes (Login)
    
+ Response 200 (application/json)
    + Headers


    + Attributes(token/refreshToken)

            
    
    + Schema

            {}

# Group Paciente

## Paciente [/paciente]

### getAllPaciente( ) [GET]

+ Request Listar Todos os Pacientes
 
    + Headers
                
            Authentication: Bearer JWT

+ Response 200 (application/json)
    + Headers
            
            token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlBhYmxvIiwiZW1haWwiOiJwYWNpZW50ZUBnbWFpbC5jb20iLCJhY3RpdmUiOiIxIiwiZXhwaXJlZF9hdCI6IjIwMTktMDctMjEgMTM6Mzc6NDEifQ.3DwABfqtU9zfc0IcnNBnwk9RalrZI_BX6jQDHCQey-A
            refresh_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhY2llbnRlQGdtYWlsLmNvbSIsImRhdGUiOnsiZGF0ZSI6IjIwMTktMDctMTkgMTM6Mzc6NDEuNzM2MjY4IiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJBbWVyaWNhXC9TYW9fUGF1bG8ifX0.aClwXOk5ggoirvDmP73e6bpvncawPPketZ6LIN55DKI
    
    + Attributes (array[Paciente.id,Paciente.id])
    + Schema

            {}

### insertPaciente( ) [POST]

+ Request Inserir Paciente

    + Headers
                
            Authentication: Bearer JWT


    + Schema

            {}

    + Attributes (Paciente)
    
+ Response 200 (application/json)
    + Headers

            token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlBhYmxvIiwiZW1haWwiOiJwYWNpZW50ZUBnbWFpbC5jb20iLCJhY3RpdmUiOiIxIiwiZXhwaXJlZF9hdCI6IjIwMTktMDctMjEgMTM6Mzc6NDEifQ.3DwABfqtU9zfc0IcnNBnwk9RalrZI_BX6jQDHCQey-A
            refresh_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhY2llbnRlQGdtYWlsLmNvbSIsImRhdGUiOnsiZGF0ZSI6IjIwMTktMDctMTkgMTM6Mzc6NDEuNzM2MjY4IiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJBbWVyaWNhXC9TYW9fUGF1bG8ifX0.aClwXOk5ggoirvDmP73e6bpvncawPPketZ6LIN55DKI
    
    + Schema

            {}


### updatePaciente( ) [PUT]

+ Request Editar Paciente 

    + Headers
                
            Authentication: Bearer JWT


    + Schema

            {}

    + Attributes (Paciente.id)
    
+ Response 200 (application/json)
    + Headers

            token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlBhYmxvIiwiZW1haWwiOiJwYWNpZW50ZUBnbWFpbC5jb20iLCJhY3RpdmUiOiIxIiwiZXhwaXJlZF9hdCI6IjIwMTktMDctMjEgMTM6Mzc6NDEifQ.3DwABfqtU9zfc0IcnNBnwk9RalrZI_BX6jQDHCQey-A
            refresh_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhY2llbnRlQGdtYWlsLmNvbSIsImRhdGUiOnsiZGF0ZSI6IjIwMTktMDctMTkgMTM6Mzc6NDEuNzM2MjY4IiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJBbWVyaWNhXC9TYW9fUGF1bG8ifX0.aClwXOk5ggoirvDmP73e6bpvncawPPketZ6LIN55DKI
    
    + Schema

            {}

### deletePaciente( ) [DELETE]

+ Request Deletar Paciente

    + Headers
                
            Authentication: Bearer JWT


    + Schema

            {}

    + Attributes (Id)
    
+ Response 200 (application/json)
    + Headers

            token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlBhYmxvIiwiZW1haWwiOiJwYWNpZW50ZUBnbWFpbC5jb20iLCJhY3RpdmUiOiIxIiwiZXhwaXJlZF9hdCI6IjIwMTktMDctMjEgMTM6Mzc6NDEifQ.3DwABfqtU9zfc0IcnNBnwk9RalrZI_BX6jQDHCQey-A
            refresh_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhY2llbnRlQGdtYWlsLmNvbSIsImRhdGUiOnsiZGF0ZSI6IjIwMTktMDctMTkgMTM6Mzc6NDEuNzM2MjY4IiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJBbWVyaWNhXC9TYW9fUGF1bG8ifX0.aClwXOk5ggoirvDmP73e6bpvncawPPketZ6LIN55DKI
    
    + Schema

            {}


# Group Exame

## Exame [/exame]

### getAllExame( ) [GET]

+ Request Listar Todos os Exames 
    + Headers
                
            Authentication: Bearer JWT


    + Schema

            {}

+ Response 200 (application/json)
    + Headers
            
            token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlBhYmxvIiwiZW1haWwiOiJwYWNpZW50ZUBnbWFpbC5jb20iLCJhY3RpdmUiOiIxIiwiZXhwaXJlZF9hdCI6IjIwMTktMDctMjEgMTM6Mzc6NDEifQ.3DwABfqtU9zfc0IcnNBnwk9RalrZI_BX6jQDHCQey-A
            refresh_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhY2llbnRlQGdtYWlsLmNvbSIsImRhdGUiOnsiZGF0ZSI6IjIwMTktMDctMTkgMTM6Mzc6NDEuNzM2MjY4IiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJBbWVyaWNhXC9TYW9fUGF1bG8ifX0.aClwXOk5ggoirvDmP73e6bpvncawPPketZ6LIN55DKI
    
    + Attributes (array[Exame.id,Exame.id])
    + Schema

            {}


### insertExame( ) [POST]

+ Request Inserir Exame 
    + Headers
                
            Authentication: Bearer JWT


    + Schema

            {}

    + Attributes (Exame)
    
+ Response 200 (application/json)
    + Headers

            token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlBhYmxvIiwiZW1haWwiOiJwYWNpZW50ZUBnbWFpbC5jb20iLCJhY3RpdmUiOiIxIiwiZXhwaXJlZF9hdCI6IjIwMTktMDctMjEgMTM6Mzc6NDEifQ.3DwABfqtU9zfc0IcnNBnwk9RalrZI_BX6jQDHCQey-A
            refresh_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhY2llbnRlQGdtYWlsLmNvbSIsImRhdGUiOnsiZGF0ZSI6IjIwMTktMDctMTkgMTM6Mzc6NDEuNzM2MjY4IiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJBbWVyaWNhXC9TYW9fUGF1bG8ifX0.aClwXOk5ggoirvDmP73e6bpvncawPPketZ6LIN55DKI
    
    + Schema

            {}


### updateExame( ) [PUT]

+ Request Editar Exame 

    + Headers
                
            Authentication: Bearer JWT
    
    + Schema

            {}

    + Attributes (Exame.id)
    
+ Response 200 (application/json)
    + Headers

            token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlBhYmxvIiwiZW1haWwiOiJwYWNpZW50ZUBnbWFpbC5jb20iLCJhY3RpdmUiOiIxIiwiZXhwaXJlZF9hdCI6IjIwMTktMDctMjEgMTM6Mzc6NDEifQ.3DwABfqtU9zfc0IcnNBnwk9RalrZI_BX6jQDHCQey-A
            refresh_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhY2llbnRlQGdtYWlsLmNvbSIsImRhdGUiOnsiZGF0ZSI6IjIwMTktMDctMTkgMTM6Mzc6NDEuNzM2MjY4IiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJBbWVyaWNhXC9TYW9fUGF1bG8ifX0.aClwXOk5ggoirvDmP73e6bpvncawPPketZ6LIN55DKI
    
    + Schema

            {}

### deleteExame( ) [DELETE]

+ Request Deletar Exame

    + Headers
                
            Authentication: Bearer JWT
    
    + Schema

            {}

    + Attributes (Id)
    
+ Response 200 (application/json)
    + Headers

            token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlBhYmxvIiwiZW1haWwiOiJwYWNpZW50ZUBnbWFpbC5jb20iLCJhY3RpdmUiOiIxIiwiZXhwaXJlZF9hdCI6IjIwMTktMDctMjEgMTM6Mzc6NDEifQ.3DwABfqtU9zfc0IcnNBnwk9RalrZI_BX6jQDHCQey-A
            refresh_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhY2llbnRlQGdtYWlsLmNvbSIsImRhdGUiOnsiZGF0ZSI6IjIwMTktMDctMTkgMTM6Mzc6NDEuNzM2MjY4IiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJBbWVyaWNhXC9TYW9fUGF1bG8ifX0.aClwXOk5ggoirvDmP73e6bpvncawPPketZ6LIN55DKI
    
    + Schema

            {}




# Group Consulta

## Consulta [/consulta]

### getAllConsulta( ) [GET]

+ Request Listar Todas as Consultas 
    + Headers
                
            Authentication: Bearer JWT


    + Schema

            {}

+ Response 200 (application/json)
    + Headers
            
            token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlBhYmxvIiwiZW1haWwiOiJwYWNpZW50ZUBnbWFpbC5jb20iLCJhY3RpdmUiOiIxIiwiZXhwaXJlZF9hdCI6IjIwMTktMDctMjEgMTM6Mzc6NDEifQ.3DwABfqtU9zfc0IcnNBnwk9RalrZI_BX6jQDHCQey-A
            refresh_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhY2llbnRlQGdtYWlsLmNvbSIsImRhdGUiOnsiZGF0ZSI6IjIwMTktMDctMTkgMTM6Mzc6NDEuNzM2MjY4IiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJBbWVyaWNhXC9TYW9fUGF1bG8ifX0.aClwXOk5ggoirvDmP73e6bpvncawPPketZ6LIN55DKI
    
    + Attributes (array[Consulta.id,Consulta.id])
    + Schema

            {}

### insertConsulta( ) [POST]

+ Request Inserir Consulta 
    + Headers
                
            Authentication: Bearer JWT


    + Schema

            {}

    + Attributes (Consulta)
    
+ Response 200 (application/json)
    + Headers

            token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlBhYmxvIiwiZW1haWwiOiJwYWNpZW50ZUBnbWFpbC5jb20iLCJhY3RpdmUiOiIxIiwiZXhwaXJlZF9hdCI6IjIwMTktMDctMjEgMTM6Mzc6NDEifQ.3DwABfqtU9zfc0IcnNBnwk9RalrZI_BX6jQDHCQey-A
            refresh_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhY2llbnRlQGdtYWlsLmNvbSIsImRhdGUiOnsiZGF0ZSI6IjIwMTktMDctMTkgMTM6Mzc6NDEuNzM2MjY4IiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJBbWVyaWNhXC9TYW9fUGF1bG8ifX0.aClwXOk5ggoirvDmP73e6bpvncawPPketZ6LIN55DKI
    
    + Schema

            {}


### updateConsulta( ) [PUT]

+ Request Editar Consulta 

    + Headers
                
            Authentication: Bearer JWT
    
    + Schema

            {}

    + Attributes (Consulta.id)
    
+ Response 200 (application/json)
    + Headers

            token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlBhYmxvIiwiZW1haWwiOiJwYWNpZW50ZUBnbWFpbC5jb20iLCJhY3RpdmUiOiIxIiwiZXhwaXJlZF9hdCI6IjIwMTktMDctMjEgMTM6Mzc6NDEifQ.3DwABfqtU9zfc0IcnNBnwk9RalrZI_BX6jQDHCQey-A
            refresh_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhY2llbnRlQGdtYWlsLmNvbSIsImRhdGUiOnsiZGF0ZSI6IjIwMTktMDctMTkgMTM6Mzc6NDEuNzM2MjY4IiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJBbWVyaWNhXC9TYW9fUGF1bG8ifX0.aClwXOk5ggoirvDmP73e6bpvncawPPketZ6LIN55DKI
    
    + Schema

            {}

### deleteConsulta( ) [DELETE]

+ Request Deletar Consulta

    + Headers
                
            Authentication: Bearer JWT
    
    + Schema

            {}

    + Attributes (Id)
    
+ Response 200 (application/json)
    + Headers

            token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlBhYmxvIiwiZW1haWwiOiJwYWNpZW50ZUBnbWFpbC5jb20iLCJhY3RpdmUiOiIxIiwiZXhwaXJlZF9hdCI6IjIwMTktMDctMjEgMTM6Mzc6NDEifQ.3DwABfqtU9zfc0IcnNBnwk9RalrZI_BX6jQDHCQey-A
            refresh_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhY2llbnRlQGdtYWlsLmNvbSIsImRhdGUiOnsiZGF0ZSI6IjIwMTktMDctMTkgMTM6Mzc6NDEuNzM2MjY4IiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJBbWVyaWNhXC9TYW9fUGF1bG8ifX0.aClwXOk5ggoirvDmP73e6bpvncawPPketZ6LIN55DKI
    
    + Schema

            {}


# Group Exercicio

## Exercicio [/exercicio]

### getAllExercicio( ) [GET]

+ Request Listar Todas os Exercicios 
    + Headers
                
            Authentication: Bearer JWT

+ Response 200 (application/json)
    + Headers
            
            token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlBhYmxvIiwiZW1haWwiOiJwYWNpZW50ZUBnbWFpbC5jb20iLCJhY3RpdmUiOiIxIiwiZXhwaXJlZF9hdCI6IjIwMTktMDctMjEgMTM6Mzc6NDEifQ.3DwABfqtU9zfc0IcnNBnwk9RalrZI_BX6jQDHCQey-A
            refresh_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhY2llbnRlQGdtYWlsLmNvbSIsImRhdGUiOnsiZGF0ZSI6IjIwMTktMDctMTkgMTM6Mzc6NDEuNzM2MjY4IiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJBbWVyaWNhXC9TYW9fUGF1bG8ifX0.aClwXOk5ggoirvDmP73e6bpvncawPPketZ6LIN55DKI
    
    + Attributes (array[Exercicio.id,Exercicio.id])
    + Schema

            {}

### insertExercicio( ) [POST]

+ Request Inserir Exercicio 
    + Headers
                
            Authentication: Bearer JWT


    + Schema

            {}


    + Attributes (Exercicio)
    
+ Response 200 (application/json)
    + Headers

            token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlBhYmxvIiwiZW1haWwiOiJwYWNpZW50ZUBnbWFpbC5jb20iLCJhY3RpdmUiOiIxIiwiZXhwaXJlZF9hdCI6IjIwMTktMDctMjEgMTM6Mzc6NDEifQ.3DwABfqtU9zfc0IcnNBnwk9RalrZI_BX6jQDHCQey-A
            refresh_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhY2llbnRlQGdtYWlsLmNvbSIsImRhdGUiOnsiZGF0ZSI6IjIwMTktMDctMTkgMTM6Mzc6NDEuNzM2MjY4IiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJBbWVyaWNhXC9TYW9fUGF1bG8ifX0.aClwXOk5ggoirvDmP73e6bpvncawPPketZ6LIN55DKI
    
    + Schema

            {}


### updateExercicio( ) [PUT]

+ Request Editar Exercicio 

    + Headers
                
            Authentication: Bearer JWT
    
    + Schema

            {}

    + Attributes (Exercicio.id)
    
+ Response 200 (application/json)
    + Headers

            token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlBhYmxvIiwiZW1haWwiOiJwYWNpZW50ZUBnbWFpbC5jb20iLCJhY3RpdmUiOiIxIiwiZXhwaXJlZF9hdCI6IjIwMTktMDctMjEgMTM6Mzc6NDEifQ.3DwABfqtU9zfc0IcnNBnwk9RalrZI_BX6jQDHCQey-A
            refresh_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhY2llbnRlQGdtYWlsLmNvbSIsImRhdGUiOnsiZGF0ZSI6IjIwMTktMDctMTkgMTM6Mzc6NDEuNzM2MjY4IiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJBbWVyaWNhXC9TYW9fUGF1bG8ifX0.aClwXOk5ggoirvDmP73e6bpvncawPPketZ6LIN55DKI
    
    + Schema

            {}

### deleteExercicio( ) [DELETE]

+ Request Deletar Exercicio

    + Headers
                
            Authentication: Bearer JWT
    
    + Schema

            {}

    + Attributes (Id)
    
+ Response 200 (application/json)
    + Headers

            token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlBhYmxvIiwiZW1haWwiOiJwYWNpZW50ZUBnbWFpbC5jb20iLCJhY3RpdmUiOiIxIiwiZXhwaXJlZF9hdCI6IjIwMTktMDctMjEgMTM6Mzc6NDEifQ.3DwABfqtU9zfc0IcnNBnwk9RalrZI_BX6jQDHCQey-A
            refresh_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhY2llbnRlQGdtYWlsLmNvbSIsImRhdGUiOnsiZGF0ZSI6IjIwMTktMDctMTkgMTM6Mzc6NDEuNzM2MjY4IiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJBbWVyaWNhXC9TYW9fUGF1bG8ifX0.aClwXOk5ggoirvDmP73e6bpvncawPPketZ6LIN55DKI
    
    + Schema

            {}

# Group Imc

## Imc [/imc]

### getAllImc( ) [GET]

+ Request Listar Todas os Imc 
    + Headers
                
            Authentication: Bearer JWT

+ Response 200 (application/json)
    + Headers
            
            token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlBhYmxvIiwiZW1haWwiOiJwYWNpZW50ZUBnbWFpbC5jb20iLCJhY3RpdmUiOiIxIiwiZXhwaXJlZF9hdCI6IjIwMTktMDctMjEgMTM6Mzc6NDEifQ.3DwABfqtU9zfc0IcnNBnwk9RalrZI_BX6jQDHCQey-A
            refresh_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhY2llbnRlQGdtYWlsLmNvbSIsImRhdGUiOnsiZGF0ZSI6IjIwMTktMDctMTkgMTM6Mzc6NDEuNzM2MjY4IiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJBbWVyaWNhXC9TYW9fUGF1bG8ifX0.aClwXOk5ggoirvDmP73e6bpvncawPPketZ6LIN55DKI
    
    + Attributes (array[Imc.id,Imc.id])
    + Schema

            {}

### insertImc( ) [POST]

+ Request Inserir Imc 

    + Headers
                
            Authentication: Bearer JWT

    + Schema

            {}


    + Attributes (Imc)
    
+ Response 200 (application/json)
    + Headers

            token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlBhYmxvIiwiZW1haWwiOiJwYWNpZW50ZUBnbWFpbC5jb20iLCJhY3RpdmUiOiIxIiwiZXhwaXJlZF9hdCI6IjIwMTktMDctMjEgMTM6Mzc6NDEifQ.3DwABfqtU9zfc0IcnNBnwk9RalrZI_BX6jQDHCQey-A
            refresh_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhY2llbnRlQGdtYWlsLmNvbSIsImRhdGUiOnsiZGF0ZSI6IjIwMTktMDctMTkgMTM6Mzc6NDEuNzM2MjY4IiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJBbWVyaWNhXC9TYW9fUGF1bG8ifX0.aClwXOk5ggoirvDmP73e6bpvncawPPketZ6LIN55DKI
    
    + Schema

            {}


### updateImc( ) [PUT]

+ Request Editar Imc 

    + Headers
                
            Authentication: Bearer JWT
    
    + Schema

            {}

    + Attributes (Imc.id)
    
+ Response 200 (application/json)
    + Headers

            token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlBhYmxvIiwiZW1haWwiOiJwYWNpZW50ZUBnbWFpbC5jb20iLCJhY3RpdmUiOiIxIiwiZXhwaXJlZF9hdCI6IjIwMTktMDctMjEgMTM6Mzc6NDEifQ.3DwABfqtU9zfc0IcnNBnwk9RalrZI_BX6jQDHCQey-A
            refresh_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhY2llbnRlQGdtYWlsLmNvbSIsImRhdGUiOnsiZGF0ZSI6IjIwMTktMDctMTkgMTM6Mzc6NDEuNzM2MjY4IiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJBbWVyaWNhXC9TYW9fUGF1bG8ifX0.aClwXOk5ggoirvDmP73e6bpvncawPPketZ6LIN55DKI
    
    + Schema

            {}

### deleteImc( ) [DELETE]

+ Request Deletar Imc

    + Headers
                
            Authentication: Bearer JWT
    
    + Schema

            {}

    + Attributes (Id)
    
+ Response 200 (application/json)
    + Headers

            token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlBhYmxvIiwiZW1haWwiOiJwYWNpZW50ZUBnbWFpbC5jb20iLCJhY3RpdmUiOiIxIiwiZXhwaXJlZF9hdCI6IjIwMTktMDctMjEgMTM6Mzc6NDEifQ.3DwABfqtU9zfc0IcnNBnwk9RalrZI_BX6jQDHCQey-A
            refresh_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhY2llbnRlQGdtYWlsLmNvbSIsImRhdGUiOnsiZGF0ZSI6IjIwMTktMDctMTkgMTM6Mzc6NDEuNzM2MjY4IiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJBbWVyaWNhXC9TYW9fUGF1bG8ifX0.aClwXOk5ggoirvDmP73e6bpvncawPPketZ6LIN55DKI
    
    + Schema

            {}




# Data Structures

## Id (object)
+ id:1 (number) 

## Paciente (object)
+ email:paciente@gmail.com (string) 
+ senha: adminadmin (string) 
+ nome:Pablo (string)  
+ nascimento:1998-09-09 (string) 
+ peso:123.99 (string) 
+ altura:1.88 (string) 
+ sexo:masculino (string) 
+ nacionalidade:Brasil (string)  
## Paciente.id (Paciente)
+ id:1 (number) 


## Exame (object)
+ nome: sangue (string)
+ local: laboratorio (string)
+ data: 2019-09-09 00:00:00 (string)
+ descricao: descreve (string)
+ idpaciente: 1 (number)
+ idmedico: 1 (number)
+ idnutricionista: 1 (number)
## Exame.id (Exame)
+ id:1 (number) 


## Consulta (object)
+ local: Hospital (string)
+ data: 2019-09-09 00:00:00 (string)
+ descricao: descreve (string)
+ idpaciente: 1 (number)
+ idmedico: 1 (number)
+ idnutricionista: 1 (number)
## Consulta.id (Consulta)
+ id:1 (number) 


## Exercicio (object)
+ nome: corrida (string)
+ descricao: descreve (string)
+ idpaciente: 1 (number)
## Exercicio.id (Exercicio)
+ id:1 (number)


## Imc (object) 
+ data:1998-09-09 (string) 
+ peso:123.99 (string) 
+ altura:1.88 (string) 
+ idpaciente: 1 (number)
## Imc.id (Imc)
+ id:1 (number) 


## Login (object) 
+ email:email@gmail.com (string) 
+ senha:adminadmin (string) 
## Login.id (Login)
+ id:1 (number) 

## token/refreshToken (object)
+ token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6IlBhYmxvIiwiZW1haWwiOiJwYWNpZW50ZUBnbWFpbC5jb20iLCJhY3RpdmUiOiIxIiwiZXhwaXJlZF9hdCI6IjIwMTktMDctMjEgMTM6Mzc6NDEifQ.3DwABfqtU9zfc0IcnNBnwk9RalrZI_BX6jQDHCQey-A
+ refresh_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBhY2llbnRlQGdtYWlsLmNvbSIsImRhdGUiOnsiZGF0ZSI6IjIwMTktMDctMTkgMTM6Mzc6NDEuNzM2MjY4IiwidGltZXpvbmVfdHlwZSI6MywidGltZXpvbmUiOiJBbWVyaWNhXC9TYW9fUGF1bG8ifX0.aClwXOk5ggoirvDmP73e6bpvncawPPketZ6LIN55DKI